name: flutter_application_stepik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_translate: ^0.0.6
  http: ^0.13.6
  provider: ^6.1.1
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
